### ISSUE TITLE
Log Error - Error doing job: Task exception was never retrieved (None)

### ISSUE THREAD

**Issue by mikegoubeaux** [jay-oswald/ha-wican#15]
I have been working on making a custom vehicle profile and it seems as I change profiles, various PIDs that were previously used are throwing errors in the logs—I no longer have an 'EngineRPM' PID in my vehicle profile.

```
Logger: homeassistant
Source: custom_components/wican/sensor.py:281
integration: WiCAN
First occurred: December 5, 2024 at 6:50:54 PM (64 occurrences)
Last logged: 10:00:29 AM

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 453, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in async_update_listeners
    update_callback()
  File "/config/custom_components/wican/sensor.py", line 277, in _handle_coordinator_update
    self.set_state()
  File "/config/custom_components/wican/sensor.py", line 281, in set_state
    state = self.coordinator.data['pid'][self.get_data('key')]['value']
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'EngineRPM'
```

**Comment by jwiesel** [comment]
Hi @mikegoubeaux, if PIDs are removed from the WiCAN devices while the integration is running, it might still rely on them.
Two ideas come to mind:
1. Have you tried reloading the integration in HomeAssistant after changing the car configuration on the WiCAN device? This should avoid the issue as the car configuration is reloaded from the car configuration.
2. Did you delete the orphan entity (EngineRPM) / delete the device and add it again?
I started adding some troubleshooting instructions here: https://github.com/jwiesel/ha-wican/tree/readme
If you have further ideas to improve it, let me know.

To prevent the error in the logs, a check could be added, if the key exists:

`if coordinator.data["pid"].get(self.get_data('key')) is not None:`

But there would still be orphan entities that need to be deleted manually after a while.
