### ISSUE TITLE
Entities unavailable

### ISSUE THREAD

**Issue by jmalm** [jay-oswald/ha-wican#18]
I have noticed that sometimes the wican entities become unavailable. Reloading the integration will sometimes bring the entities back.

I have an unrelated memory leak issue that causes Home Assistant to be restarted sometimes. It's _possible_ that this is when the wican entities become unavailable. It's also _possible_ that the device is not available at that time (because it's in sleep mode or the car is away). I will try to verify this next time the entities become unavailable. 

How does the polling work? Could it be that ha-wican doesn't try to connect often enough?

With mqtt, at least the last state published by the device would be available on the broker. Can something similar be achieved with ha-wican?

**Comment by jmalm** [comment]
I just did the following:

1. Make sure the device is in sleep mode
2. Restart Home Assistant 
    => The entities are unavailable
3. Reload the integration
    => The entities are still unavailable
3. Make the device wake up (I turned on charging) 
4. Wait 60 seconds
    => The entities are still unavailable
5. Reload the integration
    => The entities are now available

If I interpret this correctly, if the device is in sleep mode when Home Assistant restarts, the entities will not become automatically available when the device wakes up -- a manual reload of the integration is necessary.

**Comment by smurf12345** [comment]
I'm seeing the same issue.  When I restart Home Assistant, if the WiCAN is sleeping or not reachable at the time, the integration will show entities unavailable.  This makes sense.  However, the integration doesn't seem to retry once the WiCAN is reachable and a manual reload of the integration is required.

**Comment by jmalm** [comment]
Sorry for the Swedish logs below, but I'm wondering if it could have something to do with the problem that the entities do not become available when the device comes online again.

It looks like data['status'] can sometimes be a dict and sometimes False. Feels like a design that is a bit error prone?

I'm running ha-wican 0.2.1.



```
Logger: homeassistant
Källa: custom_components/wican/sensor.py:153
integration: WiCAN
Inträffade först: 31 december 2024 kl. 09:47:36 (11993 händelser)
Senast loggade: 19:59:42

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 453, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in async_update_listeners
    update_callback()
  File "/config/custom_components/wican/sensor.py", line 147, in _handle_coordinator_update
    self.set_state()
  File "/config/custom_components/wican/sensor.py", line 153, in set_state
    state = self.process_state(self.coordinator.data['status'][self.get_data('key')])
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'bool' object is not subscriptable
```

**Comment by jay-oswald** [comment]
@jmalm this is a current issue on the main branch, but if you use an auctal release version it is stable.

**Comment by jmalm** [comment]
@jay-oswald What is the latest release? The commit tagged 0.2.1?

Would you like some help getting this bug fixed? I don't know if @abstractionnl is aware of the bug. Maybe he would be best suited to fix it. I guess it was introduced by his pull request?

**Comment by abstractionnl** [comment]
This issue is due to the WiCAN needing to be available during loading of the component. This means that if home assistant restarts and your car is not home (or WiCAN is sleeping), all the entities will be gone.

To fix this, the component needs to store the entities and reload them from configuration on reload.

I switched to using MQTT because of all these issues.

**Comment by jwiesel** [comment]
Hi @jmalm , @abstractionnl ,
I just created a workaround: If the device is not available during restart of HomeAssistant, HA will automatically retry to initialize when the device becomes available - See also: https://developers.home-assistant.io/docs/integration_setup_failures
You can find it here, if you'd like to test: https://github.com/jwiesel/ha-wican/tree/skip-sensor-type

The setup of the integration might need some refactoring to avoid the errors in the HomeAssistant logs.

**Comment by jmalm** [comment]
Thanks! Trying it out now. Works as intended so far. It tried to reconnect until the device became available.

**Comment by jay-oswald** [comment]
Thanks everyone. Sorry I haven't been able to get this sorted out, I've gone from a sleepy baby to a toddler running around, so not much time at the moment.

@jmalm Yes, the latest release will always be the tagged versions, I'm treating the main branch as a dev/WIP branch. 

@jwiesel your PR looks good, hoping to be able to give it a proper test at some point. However my wife has gone to spend a week with her parents, so I've got time without the toddler in the house, however she also takes the car with the WiCAN in it, so I can't use it to sort this out.

On 2nd thought I may just merge your PR now already been confirmed by @jmalm that it works, and we know the current main branhc is already broken, so merging it in now will mean anybody using the main branch it should work for them, I'll just hold off on doing a tagged release until I've had a chance to test it myself

**Comment by jwiesel** [comment]
Thank you @jay-oswald !
All the best for you and your family!

**Comment by jay-oswald** [comment]
Closing off this one, the bug was never officially released, and now the fix it in, but also still not officially released
